apiVersion: v1
kind: List
metadata:
  name: springhellotest
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: springhellotest
      name: springhellotest
    spec:
      replicas: 1
      selector:
        app: springhellotest
        deploymentconfig: springhellotest
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: springhellotest
            deploymentconfig: springhellotest
        spec:
          containers:
            - name: onurkaratas/springbootlatest
              image: docker.io/onurkaratas/springbootlatest:latest
              imagePullPolicy: Always
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 200m
                  memory: 512Mi
              ports:
                - containerPort: 8080
                  protocol: TCP
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - onurkaratas/springbootlatest:latest
            from:
              kind: ImageStreamTag
              name: onurkaratas/springbootlatest:latest
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: springhellotest
      name: springhellotest
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: springhellotest
        deploymentconfig: springhellotest
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: springhellotest
      name: springhellotest
    spec:
      host: springhellotest-onurkaratas-crt-dev.apps.sandbox.x8i5.p1.openshiftapps.com
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: springhellotest
        weight: 100
      wildcardPolicy: None