kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "springhellotest"
spec:
  source:
    #contextDir: deployment/openshift
    git:
      uri: "https://github.com/Onurkaratas1/hello-java-spring.git"
      ref: "main"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline